### ISSUE TITLE
Create About us page

### ISSUE THREAD

**Issue by Wajahat-Mirza** [software-students-fall2021/project-setup-potluck#51]
## Estimation of work
- TBD

## Acceptance criteria
- Create About us page that explains what PotLuck is, who are the team members, etc

**Comment by seungguini** [comment]
Hey Waj, remember to set the Sprint to Sprint 2. Also, the tasks 
can be set up as check marks if you use the square brackets! 👍🏼 

- [ ] Like this [ ]

**Comment by Wajahat-Mirza** [comment]
PR was created and merge: https://github.com/software-students-fall2021/project-setup-potluck/pull/49
